server:
  port: 8080
  
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
      
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/studyapplication?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 'admin'
    hikari: 
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
  jpa:
    show-sql: true
    #generate-ddl: true #to create tables
    #hibernate:
      #ddl-auto: create #to always drop and create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  
    
    
      
      
