server:
  port: 8080
  
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
      
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/studyapplication?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 'admin'
    hikari: 
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
  flyway:
    locations: classpath:db/migration,classpath:db/datatest    
  jpa:
    show-sql: true
    #generate-ddl: true #to create tables
    #hibernate:
      #ddl-auto: none #to always drop and create tables
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/ddl.sql
  jackson:
    deserialization:
      fail-on-unknown-properties: true #when we decide not accept properties passed in the request that not exist
      fail-on-ignored-properties: true #when we decide not accept properties passed in the request that exist but ignored
  data:
    web:
      pageable:
        size-parameter: registros
  
  mail:
    sendgrid:
      host: smtp.sendgrid.net
      port: 587
      username: apikey
      password: ~
      sender: StudyApplication <notreply@studyapplication.com.br>
    gmail:
      host: smtp.gmail.com
      port: 587
      username: ~
      password: ~
      protocol: smtp
      properties-mail-smtp-auth: true
      properties-mail-smtp-starttls-enable: true
      properties-mail-smtp-ssl-trust: smtp.gmail.com  
studyapplication:
  storage:
    storageType: local
    local:
      photos: /home/rodrigo/Pictures/study
    s3:  
      access-key: ~
      access-secret: ~
      bucket: studyapplication-test
      region: us-east-1
      directory: files
  mail:
    service: gmail
